import{i as l,S as p}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h="45358562-a6f601b45a643dd81cb1b87d3",y="https://pixabay.com/api/";function g(n){const o=`${y}?key=${h}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(t=>{if(!t.ok)throw new Error("Failed to fetch images");return t.json()}).then(t=>t.hits).catch(t=>{throw console.error("Error:",t),t})}function b(n){const o=document.getElementById("gallery");o.innerHTML="";const t=n.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:d,comments:f,downloads:m})=>`
        <a href="${e}" class="gallery-item">
            <img src="${s}" alt="${r}" />
            <div class="info">
                <p> Likes ${i}</p>
                <p> Views ${d}</p>
                <p> Comments ${f}</p>
                <p> Downloads ${m}</p>
            </div>
        </a>`).join("");o.insertAdjacentHTML("beforeend",t)}function c(n){console.error("Rendering error message:",n),l.error({title:"Error",message:n,position:"topRight"})}let a;const u=document.querySelector("#loader");document.querySelector("#search-form").addEventListener("submit",async function(n){n.preventDefault();const o=document.getElementById("search-input").value.trim();if(o===""){l.error({title:"Error",message:"Search field cannot be empty.",position:"topRight"});return}L();try{const t=await g(o);t.length>0?(b(t),$()):c("Sorry, there are no images matching your search query. Please try again!")}catch(t){c(t.message)}finally{E()}});function L(){u.style.display="block"}function E(){u.style.display="none"}function $(){a?a.refresh():a=new p(".gallery-item",{captionsData:"alt",captionDelay:250})}
//# sourceMappingURL=commonHelpers.js.map
